ddb bash scripts

diff --git a/backend-flask/bin/ddb/drop b/backend-flask/bin/ddb/drop
--- a/backend-flask/bin/ddb/drop
+++ b/backend-flask/bin/ddb/drop
@@ -1,67 +1,20 @@
-#!/usr/bin/env python3
+#! /usr/bin/bash
 
-import boto3 
-import sys
+set -e # stop if it fails at any point
 
-attrs = {
-    'endpoint_url': 'http://localhost:8000'
-}
+if [ -z "$1" ]; then
+  echo "No TABLE_NAME argument supplied eg ./bin/ddb/drop cruddur-messages prod "
+  exit 1
+fi
+TABLE_NAME=$1
 
-if len(sys.argv) == 2:
-    if "prod" in sys.argv[1]:
-        attrs = {}
+if [ "$2" = "prod" ]; then
+  ENDPOINT_URL=""
+else
+  ENDPOINT_URL="--endpoint-url=http://localhost:8000"
+fi
 
-ddb = boto3.clinet('dynamodb', **attrs)
-table_name = 'crudder-message'
+echo "deleting table: $TABLE_NAME"
 
-response = ddb.create_table(
-    TableName=table_name,
-    AttributeDefinitions=[
-        {
-            'AttributeName': 'pk',
-            'AttributeType': 'S'
-        },
-        {
-            'AttributeName': 'sk',
-            'AttributeType': 'S'
-        },
-    ],
-        KeySchema=[
-        {
-            'AttributeName': 'pk',
-            'KeyType': 'HASH'
-        },
-        {
-            'AttributeName': 'sk',
-            'KeyType': 'RANGE'
-        },
-    ],
-    # GlobalSecondaryIndexes=[
-    #     {
-    #         'IndexName': 'string',
-    #         'KeySchema': [
-    #             {
-    #                 'AttributeName': 'string',
-    #                 'KeyType': 'HASH'|'RANGE'
-    #             },
-    #         ],
-    #         'Projection': {
-    #             'ProjectionType': 'ALL'|'KEYS_ONLY'|'INCLUDE',
-    #             'NonKeyAttributes': [
-    #                 'string',
-    #             ]
-    #         },
-    #         'ProvisionedThroughput': {
-    #             'ReadCapacityUnits': 123,
-    #             'WriteCapacityUnits': 123
-    #         }
-    #     },
-    # ],
-    BillingMode='PROVISIONED',
-    ProvisionedThroughput={
-        'ReadCapacityUnits': 5,
-        'WriteCapacityUnits': 5
-    }
-)
-
-print(response)
+aws dynamodb delete-table $ENDPOINT_URL \
+  --table-name $TABLE_NAME
